name: ci-go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Execute
      run: sudo ./bpflsmprobe
